### ISSUE TITLE
Doesnt work with IntelliJ 14.1.5

### ISSUE THREAD

**Issue by vtmoren** [fioan89/sourcesync#24]
Doesn't load after install on IntelliJ 14.1.5.

**Comment by harscoet** [comment]
:+1:

**Comment by vtmoren** [comment]
PluginException: cannot create class "org.wavescale.sourcesync.action.ActionLocalFileToRemote" [Plugin: org.wavescale.sourcesync]
PluginException: cannot create class "org.wavescale.sourcesync.action.ActionProjectConnectionConfig" [Plugin: org.wavescale.sourcesync]
PluginException: cannot create class "org.wavescale.sourcesync.action.ActionSourceSyncMenu" [Plugin: org.wavescale.sourcesync]

**Comment by fioan89** [comment]
Fixed with version 1.8 (in the plugin repository)

**Comment by vtmoren** [comment]
I have 14.1.7 and version 1.9 and the plugin still isn't working.

**Comment by fioan89** [comment]
Based on https://github.com/fioan89/sourcesync/issues/28 seems like the issue was the JDK version used by IntelliJ.
